-- Esquema H2 (modo PostgreSQL) para tests de provider-service

CREATE TABLE IF NOT EXISTS evento_procesado (
    event_id     VARCHAR(64)   PRIMARY KEY,
    event_type   VARCHAR(100)  NOT NULL,
    service      VARCHAR(50)   NOT NULL,
    aggregate_id BIGINT,
    payload      TEXT,
    procesado_en TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS persona (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100)    NOT NULL,
    primer_apellido     VARCHAR(100)    NOT NULL,
    segundo_apellido    VARCHAR(100),
    ci                  VARCHAR(20)     NOT NULL,
    telefono            VARCHAR(20),
    email               VARCHAR(150),
    fecha_nacimiento    DATE,
    genero              CHAR(1)         NOT NULL DEFAULT 'O',
    direccion_id        BIGINT,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ciudad (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100)    NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estado (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100)    NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS direccion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle           VARCHAR(255),
    numero          VARCHAR(20),
    piso            VARCHAR(20),
    apartamento     VARCHAR(20),
    referencia      VARCHAR(255),
    latitud         NUMERIC(10, 7),
    longitud        NUMERIC(10, 7),
    ciudad_id       BIGINT,
    estado_id       BIGINT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(50)     NOT NULL,
    descripcion     VARCHAR(255),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS usuario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50)     NOT NULL,
    password            VARCHAR(255)    NOT NULL,
    persona_id          BIGINT          NOT NULL,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    ultimo_acceso       TIMESTAMP,
    intentos_fallidos   INTEGER         NOT NULL DEFAULT 0,
    bloqueado           BOOLEAN         NOT NULL DEFAULT FALSE,
    token_refresh       VARCHAR(255),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS usuario_rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT          NOT NULL,
    rol_id          BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS servicio (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100)    NOT NULL,
    descripcion         VARCHAR(1000),
    duracion_minutos    INTEGER         NOT NULL DEFAULT 60,
    precio_base         NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    imagen_url          VARCHAR(500),
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    categoria           VARCHAR(50),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id              BIGINT          NOT NULL,
    usuario_id              BIGINT          NOT NULL,
    empresa                 VARCHAR(150),
    latitud                 NUMERIC(10, 7),
    longitud                NUMERIC(10, 7),
    radio_cobertura_km      NUMERIC(5, 2)   DEFAULT 10.00,
    descripcion             VARCHAR(1000),
    verificado              BOOLEAN         NOT NULL DEFAULT FALSE,
    calificacion            NUMERIC(3, 2)   DEFAULT 0.00,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor_servicio (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        BIGINT          NOT NULL,
    nombre              VARCHAR(100)    NOT NULL,
    descripcion         TEXT,
    categoria           VARCHAR(30)     NOT NULL,
    duracion_minutos    INTEGER         NOT NULL DEFAULT 60,
    precio_base         NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    requiere_certificado BOOLEAN        NOT NULL DEFAULT FALSE,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS promocion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        BIGINT,
    servicio_id         BIGINT,
    codigo              VARCHAR(30)     NOT NULL,
    nombre              VARCHAR(100)    NOT NULL,
    descripcion         TEXT,
    tipo_descuento      VARCHAR(20)     NOT NULL,
    valor_descuento     NUMERIC(10, 2)  NOT NULL,
    fecha_inicio        TIMESTAMP       NOT NULL,
    fecha_fin           TIMESTAMP       NOT NULL,
    activa              BOOLEAN         NOT NULL DEFAULT TRUE,
    limite_usos         INTEGER,
    usos_actuales       INTEGER         NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor_especialidad (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id    BIGINT          NOT NULL,
    servicio_id     BIGINT          NOT NULL,
    requiere_certificado BOOLEAN    NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor_servicio_modalidad (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_servicio_id BIGINT    NOT NULL,
    modalidad           VARCHAR(30)  NOT NULL,
    costo_adicional     NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS disponibilidad (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        BIGINT          NOT NULL,
    servicio_id         BIGINT          NOT NULL,
    dia_semana          INTEGER         NOT NULL,
    hora_inicio         TIME            NOT NULL,
    hora_fin            TIME            NOT NULL,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS solicitud_reserva (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id        BIGINT          NOT NULL,
    codigo            VARCHAR(20)     NOT NULL,
    cliente_id        BIGINT          NOT NULL,
    cliente_nombre    VARCHAR(255),
    proveedor_id      BIGINT          NOT NULL,
    proveedor_empresa VARCHAR(150),
    servicio_id       BIGINT          NOT NULL,
    servicio_nombre   VARCHAR(100),
    mascota_id        BIGINT,
    mascota_nombre    VARCHAR(100),
    fecha_inicio      TIMESTAMP,
    hora_inicio       TIME,
    precio_total      NUMERIC(10, 2),
    modalidad_entrega VARCHAR(30),
    estado            VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE',
    motivo_rechazo    TEXT,
    registro_vacunacion_id BIGINT,
    latitud           NUMERIC(10, 7),
    longitud          NUMERIC(10, 7),
    direccion_referencia VARCHAR(255),
    creada_en         TIMESTAMP       NOT NULL DEFAULT NOW(),
    respondida_en     TIMESTAMP,
    CONSTRAINT uk_solicitud_reserva_reserva_proveedor UNIQUE (reserva_id, proveedor_id)
);

CREATE TABLE IF NOT EXISTS reserva (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20)     NOT NULL,
    cliente_id          BIGINT          NOT NULL,
    proveedor_id        BIGINT,
    servicio_id         BIGINT          NOT NULL,
    mascota_id          BIGINT          NOT NULL,
    estado_reserva_id   BIGINT          NOT NULL,
    registro_vacunacion_id BIGINT,
    modalidad_entrega   VARCHAR(30),
    fecha_reserva       DATE,
    fecha_inicio        DATE            NOT NULL,
    fecha_fin           DATE,
    hora_inicio         TIME            NOT NULL,
    hora_fin            TIME,
    latitud             NUMERIC(10, 7),
    longitud            NUMERIC(10, 7),
    direccion_referencia VARCHAR(255),
    notas               VARCHAR(1000),
    precio_total        NUMERIC(10, 2),
    motivo_rechazo      VARCHAR(1000),
    respuesta_en        TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);
