server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: provider-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/petcaredb_provider
    username: postgres
    password: 123qwe
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/La_Paz
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: bo.capital.tec.pet.modules.proveedor.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

jwt:
  secret: ${JWT_SECRET:PETCareSecretKeyForJWTTokenGeneration2024VeryLongAndSecureKeyMustBe256Bits}
  expiration: 3600000
  refresh-expiration: 604800000

app:
  microservices:
    reservation:
      base-url: ${RESERVATION_SERVICE_URL:http://localhost:8081}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    group-id: provider-service
    topic:
      reserva-aceptada: reserva.aceptada
      reserva-rechazada: reserva.rechazada
      comando-notificar-proveedor: saga.comando.notificar-proveedor
      dlt: saga.dlt.v1
    partitions: 3
    replication-factor: 1
    retention-ms: 604800000

logging:
  level:
    bo.capital.tec.pet: DEBUG
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
