-- Esquema H2 (modo PostgreSQL) para tests de payment-service

CREATE TABLE IF NOT EXISTS evento_procesado (
    event_id     VARCHAR(64)   PRIMARY KEY,
    event_type   VARCHAR(100)  NOT NULL,
    service      VARCHAR(50)   NOT NULL,
    aggregate_id BIGINT,
    payload      TEXT,
    procesado_en TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS persona (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100)    NOT NULL,
    primer_apellido     VARCHAR(100)    NOT NULL,
    segundo_apellido    VARCHAR(100),
    ci                  VARCHAR(20)     NOT NULL,
    telefono            VARCHAR(20),
    email               VARCHAR(150),
    fecha_nacimiento    DATE,
    genero              CHAR(1)         NOT NULL DEFAULT 'O',
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(50)     NOT NULL,
    descripcion     VARCHAR(255),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS usuario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50)     NOT NULL,
    password            VARCHAR(255)    NOT NULL,
    persona_id          BIGINT          NOT NULL,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    intentos_fallidos   INTEGER         NOT NULL DEFAULT 0,
    bloqueado           BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS usuario_rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT          NOT NULL,
    rol_id          BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    version         INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS reserva (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20)     NOT NULL,
    cliente_id          BIGINT          NOT NULL,
    proveedor_id        BIGINT,
    servicio_id         BIGINT          NOT NULL,
    mascota_id          BIGINT          NOT NULL,
    estado_reserva_id   BIGINT          NOT NULL,
    modalidad_entrega   VARCHAR(30),
    fecha_inicio        DATE            NOT NULL,
    hora_inicio         TIME            NOT NULL,
    precio_total        NUMERIC(10, 2),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor_servicio (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        BIGINT          NOT NULL,
    nombre              VARCHAR(100)    NOT NULL,
    categoria           VARCHAR(30)     NOT NULL,
    duracion_minutos    INTEGER         NOT NULL DEFAULT 60,
    precio_base         NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    requiere_certificado BOOLEAN        NOT NULL DEFAULT FALSE,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS proveedor_servicio_modalidad (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_servicio_id   BIGINT          NOT NULL,
    modalidad               VARCHAR(30)     NOT NULL,
    costo_adicional         NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    activo                  BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted                 BOOLEAN         NOT NULL DEFAULT FALSE,
    version                 INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS promocion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        BIGINT,
    servicio_id         BIGINT,
    codigo              VARCHAR(30)     NOT NULL,
    nombre              VARCHAR(100)    NOT NULL,
    descripcion         TEXT,
    tipo_descuento      VARCHAR(20)     NOT NULL,
    valor_descuento     NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    fecha_inicio        TIMESTAMP       NOT NULL,
    fecha_fin           TIMESTAMP       NOT NULL,
    activa              BOOLEAN         NOT NULL DEFAULT TRUE,
    limite_usos         INTEGER,
    usos_actuales       INTEGER         NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    version             INTEGER         NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS pago (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id              BIGINT          NOT NULL,
    monto                   NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    metodo_pago             VARCHAR(30)     NOT NULL,
    estado_pago             VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE',
    referencia_transaccion  VARCHAR(100),
    fecha_pago              TIMESTAMP,
    comprobante_url         VARCHAR(500),
    modalidad_pago          VARCHAR(20)     NOT NULL DEFAULT 'EN_ESTABLECIMIENTO',
    intencion_id            VARCHAR(100),
    monto_original          NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    descuento_total         NUMERIC(10, 2)  NOT NULL DEFAULT 0.00,
    descuento_id            BIGINT,
    descuento_codigo        VARCHAR(30),
    descuento_nombre        VARCHAR(100),
    descuento_tipo          VARCHAR(20),
    descuento_servicio_id   BIGINT,
    estado_sync             VARCHAR(20),
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    deleted                 BOOLEAN         NOT NULL DEFAULT FALSE,
    version                 INTEGER         NOT NULL DEFAULT 1
);
