-- Esquema H2 (modo PostgreSQL) para tests de saga-orchestrator

CREATE TABLE IF NOT EXISTS evento_procesado (
    event_id     VARCHAR(64)   PRIMARY KEY,
    event_type   VARCHAR(100)  NOT NULL,
    service      VARCHAR(50)   NOT NULL,
    aggregate_id BIGINT,
    payload      TEXT,
    procesado_en TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS saga_estado (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id       BIGINT        NOT NULL,
    codigo_reserva   VARCHAR(20)   NOT NULL,
    estado           VARCHAR(30)   NOT NULL,
    paso_actual      VARCHAR(255),
    motivo           TEXT,
    ultimo_evento_id VARCHAR(64),
    creada_en        TIMESTAMP     NOT NULL DEFAULT NOW(),
    actualizada_en   TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_saga_estado_reserva_id ON saga_estado (reserva_id);
